# User settings
data:
    dir: "data"
    # Input
    input_calib: "calibration.yaml"
    input_vid: "video.mp4"
    vid_stack: "horizontal" # "vertical" or "horizontal"
    is_to_rectify: True # Set `True` if the video is not rectified yet!
    # The images in the video will be rectified and stored in:
    subdir_stereo_l: "left"
    subdir_stereo_r: "right"
    im_format: ".png" # Images will be saved in this format
    # Output 1: centre point labels
    subdir_output_l: "left_kpts"
    subdir_output_r: "right_kpts"
    # Output 2: bounding boxes around centre point
    gt_sphere_rad_mm: 2.5 # Sphere radius around kpt for ground-truth bboxes
    file_output_gt: "gt_rectified_{}.yaml"
# Interface keys
key:
    quit: "q"
    im_prev: "a" # Go to previous image pair
    im_next: "d" # Go to next image pair
    id_prev: "s" # Go to previous id
    id_next: "w" # Go to next id
    elimin: "e"  # Eliminate selected keypoints
    interp: "i"  # Interpolation
    visible: "v" # Is kpt visible in both stereo images? - TOGGLE key
    diffclt: "m" # Is kpt difficult to label? - TOGGLE key
    range: "r"   # Range
    zoom: "z"    # Toggle zoom-mode
    gtruth: "g"  # Get ground-truth bounding-boxes
# Code configuration
vis:
    window_name: "Stereo-matches labeller"
    guide: # Horizontal guide line
        thick_pxl: 1 # thickness in [pixels]
        color: [0, 255, 0] # [B, G, R]
    bar: # Status bar (at the bottom of the images)
        h_pxl: 50 # Bar height in [pixels]
        m_l_pxl: 10 # Margin on the left in [pixels]
        text_h_pxl: 25 # Text height in [pixels], must be smaller than `h_pxl`
        text_color: [255, 255, 255] # [B, G, R]
    kpt:
        c_thick_pxl: 1 # Cross thickness in [pixels]
        c_size_pxl: 25 # Cross size in [pixels]
        color_s: [0, 0, 255] # [B, G, R] Selected
        color_not_s: [0, 255, 0] # [B, G, R] Not selected
        s_thick_pxl: 3 # Outer square thickness [pixels]
        id_v_marg_pxl: 10 # Vertical margin [pixels]
    zoom: # for the zoom-mode
        color: [255, 0, 0] # [B, G, R]
        rect_w_pxl: 200 # Rectangle width in [pixels]
        rect_h_pxl: 150 # Rectangle height in [pixels]
        thick_pxl: 3    # thickness in [pixels] of the rectangle
