# User settings
data:
    dir: "data"
    subdir_stereo_l: "left"
    subdir_stereo_r: "right"
    im_format: ".png"
key: # Interface keys
    quit: "q"
    im_prev: "a" # Go to previous image pair
    im_next: "d" # Go to next image pair
    id_prev: "s" # Go to previous id
    id_next: "w" # Go to next id
    readjust: "r" # Use the arrow keys to readjust
    magic: "m" # Magic labeling -> interpolation
# Code configuration
vis:
    guide: # Horizontal guide line
        thick_pxl: 1 # thickness
        color: [0, 255, 0] # [B, G, R]
    bar: # Status bar (at the bottom of the images)
        h_pxl: 50 # Bar height in pixels
        text_h_pxl: 25 # Text size, must be smaller than `h_pxl`
        text_color: [255, 255, 255] # [B, G, R]
